### ISSUE TITLE
絵といっしょにタイトルと作成日が知りたい

### ISSUE THREAD

**Issue by alitaso345** [pps5/AlitasoFan#2]
@pps5 

[![https://gyazo.com/830ce19c10cfe55ff021b7a01bb45c56](https://i.gyazo.com/830ce19c10cfe55ff021b7a01bb45c56.png)](https://gyazo.com/830ce19c10cfe55ff021b7a01bb45c56)

元画像は版権があるから厳しいけど，タイトルと作成年月日は確かに一緒に見たい

**Comment by pps5** [comment]
元画像が公式のもので見れるのであればリンクを貼るとか。
タイトルと作成日は土日に対応します。

**Comment by alitaso345** [comment]
参考にしてる画像，大半がアニメまとめサイトのスクショとかwikiに載ってる画像なんすよねぇ...
ちょっと厳しそう

タイトルと作成日対応ありがてぇ，お願いします

**Comment by pps5** [comment]
厳しそう

タイトルはキャラ名でいいんですかね
