### ISSUE TITLE
管理ページから絵を投稿したい

### ISSUE THREAD

**Issue by alitaso345** [pps5/AlitasoFan#3]
@pps5 

## やりたいこと
管理ページから描いた絵の投稿やタイトルを更新したい．
現状だとTwiterに投稿してからinabにシコシコ更新してもらってるのでなんか申し訳ない

**Comment by pps5** [comment]
今いくつか考えてて、

- アカウントを用意して、そこにツイートのリンク、キャラ名とかをリプライで送る
- 「画像URL キャラ名（作品名） \#ありたそ画展」みたいな特定フォーマットのツイートを監視

あたりが妥当かなと。
適当なbot用意して、自動コミットするようにしたい。

**Comment by alitaso345** [comment]
botで監視，自動コミット，デプロイよさそう
その選択肢だったら個人的には「キャラ名(作品名) #ありたそ画展」でツイートを監視してもらうほうがいいな

ツイート監視botの作るのはシュッとできそう
ただcommitまでさせるbotのイメージがうまくできないのだけど，どんなかんじなのだろう？

いっそ動的アプリケーションにしちゃったほうが楽なんじゃないかと思うのだけどどう思います？

![arc](https://cloud.githubusercontent.com/assets/5152601/20048152/bc4d53fe-a4fd-11e6-9574-aa908381dd22.png)

**Comment by pps5** [comment]
1. フォーマットに沿うツイートを監視
1. git pull
2. Twitterから画像ダウンロードし、imgフォルダに保存
3. HTMLにテンプレート通り挿入
4. commit & pull
5. コンフリクトしたらなんとか頑張る。

こんな感じで考えてた。

動的アプリケーションも考えたけど、自分が詳しくないのと、上にかいたbot形式だとTwitter経由でアクセスしてサーバはgithub pagesだから、WEB→botのアクセスの必要ないので、セキュリティとかめんどい事考えなくていいかなと。

監視用にはラズパイとかそのあたり考えてます。

**Comment by alitaso345** [comment]
なるほど．余裕あったら動的アプリケーションverをPR送るので(僕のスキルセット的にレールズ+MySQL, botもRuby製, ホスティングはAWSかHeroku)万が一よさそうってなったら使ってみてください

**Comment by pps5** [comment]
Ruby（+Rails）勉強しておきます。

**Comment by alitaso345** [comment]
inabが使いたい言語 or フレームワークあったらそれに合わせるぞい

**Comment by pps5** [comment]
Python、Javaくらいしかまともに使えないので、やるとしたらpythonですかね。
Rubyでもいいですよ。

**Comment by alitaso345** [comment]
リニューアルして投稿できるようになったのでclose
