### ISSUE TITLE
ログアウト機能の実装

### ISSUE THREAD

**Issue by alitaso345** [pps5/AlitasoFan#7]
@pps5 
## やりたいこと
Twitterのログアウト機能の実装

試しに別アカウントでログインしようとしたら，そもそもログアウト機能がなかった

**Comment by pps5** [comment]
実装したけど，Twitter自体でログアウトしてるか，アプリ連携を切らない限り，勝手に以前ログアウトしたやつでログインされるっぽい．

**Comment by alitaso345** [comment]
それはtwitter authの仕様上しょうがないっぽいし，それでよさそう
closeします
