### ISSUE TITLE
@alitaso345以外のユーザーも画像投稿リンクが表示されるバグ

### ISSUE THREAD

**Issue by alitaso345** [pps5/AlitasoFan#8]
@pps5 
## 問題
表示名が「ありたそ」となっているユーザーであれば，誰でも投稿ができてしまうバグがある
該当コード↓
https://github.com/pps5/AlitasoFan/commit/e86b7fc9358a02f296f381197417c76c32f01d45#diff-42f69825340f0b5fa628d80900a46daaR34

試しに僕の適当なアカウントの表示名を「ありたそ」にしたら投稿のリンクが出てきた
<img src="https://i.gyazo.com/a5ee7834bdf64118a09960c10a821ca4.png" />

ユーザーオブジェクトの中身見てないから具体的なプロパティ名は分からないけど， `displayName` じゃなくて `screenName` とか`userId` とかuniqueな値を使ったほうがよさそう？

**Comment by pps5** [comment]
@alitaso345 

そこで判定してるのは投稿画面(post.html)へのリンク表示についてだけで問題ないです．
firebaseのconsole上で設定したルールで許可されたuidのユーザしか投稿できないようになってます．
そしてありたそのuidわからないからありたそもまだ投稿できないです．
別途確認方法教えるのであとで教えてください．

ユーザオブジェクトは```displayName```か```uid```くらいしか判定に使えそうな情報が得られなくて，問題はないけど，ありたその```uid```がまるまるコードから見えるようになるのはアレかと思って一応```displayName```で判定してます．
https://firebase.google.com/docs/reference/js/firebase.User?hl=ja

**Comment by alitaso345** [comment]
登録が正常に出来たら，その旨の表示がされるとうれしいですね．心配になって何回も登録押しちゃう
